# -*- mode: python -*-

block_cipher = None


a = Analysis(['..\\hindsight.py'],
             pathex=['..'],
             binaries=[],
             datas=[('..\\pyhindsight\\plugins', 'plugins'), ('..\\hindsight.py', 'hindsight.py')],
             hiddenimports=[
                "pycryptodome", "pyhindsight", "pyhindsight.plugins.chrome_extensions",
                "pyhindsight.plugins.generic_timestamps", "pyhindsight.plugins.google_analytics",
                "pyhindsight.plugins.google_searches", "pyhindsight.plugins.load_balancer_cookies",
                "pyhindsight.plugins.quantcast_cookies", "pyhindsight.plugins.query_string_parser",
                "pyhindsight.plugins.time_discrepancy_finder", "pyhindsight.plugins.unfurl_interpretation",
                "unfurl.parsers.parse_base64",
                "unfurl.parsers.parse_bing",
                "unfurl.parsers.parse_compressed",
                "unfurl.parsers.parse_discord",
                "unfurl.parsers.parse_domain",
                "unfurl.parsers.parse_dropbox",
                "unfurl.parsers.parse_duckduckgo",
                "unfurl.parsers.parse_google",
                "unfurl.parsers.parse_hash",
                "unfurl.parsers.parse_json",
                "unfurl.parsers.parse_ksuid",
                "unfurl.parsers.parse_mac_addr",
                "unfurl.parsers.parse_magnet",
                "unfurl.parsers.parse_mastodon",
                "unfurl.parsers.parse_mailto",
                "unfurl.parsers.parse_metasploit",
                "unfurl.parsers.parse_protobuf",
                "unfurl.parsers.parse_shortlink",
                "unfurl.parsers.parse_sonyflake",
                "unfurl.parsers.parse_tiktok",
                "unfurl.parsers.parse_timestamp",
                "unfurl.parsers.parse_twitter",
                "unfurl.parsers.parse_ulid",
                "unfurl.parsers.parse_url",
                "unfurl.parsers.parse_uuid",
                "unfurl.parsers.parse_youtube",
                "unfurl.parsers.parse_yahoo"
                ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='hindsight',
          debug=False,
          strip=False,
          upx=True,
          console=True,
          version='file_version_info_cmd.txt',
          icon='..\\pyhindsight\\static\\h.ico')