# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/app_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/app_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import extension_specifics_pb2 as components_dot_sync_dot_protocol_dot_extension__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,components/sync/protocol/app_specifics.proto\x12\x07sync_pb\x1a\x32\x63omponents/sync/protocol/extension_specifics.proto\"\x8f\x01\n\x17\x41ppNotificationSettings\x12\x30\n\x12initial_setup_done\x18\x01 \x01(\x08\x42\x02\x18\x01R\x10initialSetupDone\x12\x1a\n\x08\x64isabled\x18\x02 \x01(\x08R\x08\x64isabled\x12&\n\x0foauth_client_id\x18\x03 \x01(\tR\roauthClientId\"9\n\x11LinkedAppIconInfo\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n\x04size\x18\x02 \x01(\rR\x04size\"\xd3\x05\n\x0c\x41ppSpecifics\x12\x39\n\textension\x18\x01 \x01(\x0b\x32\x1b.sync_pb.ExtensionSpecificsR\textension\x12U\n\x15notification_settings\x18\x02 \x01(\x0b\x32 .sync_pb.AppNotificationSettingsR\x14notificationSettings\x12,\n\x12\x61pp_launch_ordinal\x18\x03 \x01(\tR\x10\x61ppLaunchOrdinal\x12!\n\x0cpage_ordinal\x18\x04 \x01(\tR\x0bpageOrdinal\x12\x41\n\x0blaunch_type\x18\x05 \x01(\x0e\x32 .sync_pb.AppSpecifics.LaunchTypeR\nlaunchType\x12,\n\x10\x62ookmark_app_url\x18\x06 \x01(\tB\x02\x18\x01R\x0e\x62ookmarkAppUrl\x12<\n\x18\x62ookmark_app_description\x18\x07 \x01(\tB\x02\x18\x01R\x16\x62ookmarkAppDescription\x12\x39\n\x17\x62ookmark_app_icon_color\x18\x08 \x01(\tB\x02\x18\x01R\x14\x62ookmarkAppIconColor\x12\x44\n\x10linked_app_icons\x18\t \x03(\x0b\x32\x1a.sync_pb.LinkedAppIconInfoR\x0elinkedAppIcons\x12\x30\n\x12\x62ookmark_app_scope\x18\n \x01(\tB\x02\x18\x01R\x10\x62ookmarkAppScope\x12;\n\x18\x62ookmark_app_theme_color\x18\x0b \x01(\rB\x02\x18\x01R\x15\x62ookmarkAppThemeColor\"A\n\nLaunchType\x12\n\n\x06PINNED\x10\x00\x12\x0b\n\x07REGULAR\x10\x01\x12\x0e\n\nFULLSCREEN\x10\x02\x12\n\n\x06WINDOW\x10\x03\x42Z\n\x0b\x63om.sync_pbB\x11\x41ppSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.app_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\021AppSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_APPNOTIFICATIONSETTINGS'].fields_by_name['initial_setup_done']._loaded_options = None
  _globals['_APPNOTIFICATIONSETTINGS'].fields_by_name['initial_setup_done']._serialized_options = b'\030\001'
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_url']._loaded_options = None
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_url']._serialized_options = b'\030\001'
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_description']._loaded_options = None
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_description']._serialized_options = b'\030\001'
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_icon_color']._loaded_options = None
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_icon_color']._serialized_options = b'\030\001'
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_scope']._loaded_options = None
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_scope']._serialized_options = b'\030\001'
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_theme_color']._loaded_options = None
  _globals['_APPSPECIFICS'].fields_by_name['bookmark_app_theme_color']._serialized_options = b'\030\001'
  _globals['_APPNOTIFICATIONSETTINGS']._serialized_start=110
  _globals['_APPNOTIFICATIONSETTINGS']._serialized_end=253
  _globals['_LINKEDAPPICONINFO']._serialized_start=255
  _globals['_LINKEDAPPICONINFO']._serialized_end=312
  _globals['_APPSPECIFICS']._serialized_start=315
  _globals['_APPSPECIFICS']._serialized_end=1038
  _globals['_APPSPECIFICS_LAUNCHTYPE']._serialized_start=973
  _globals['_APPSPECIFICS_LAUNCHTYPE']._serialized_end=1038
# @@protoc_insertion_point(module_scope)
