# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/app_setting_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/app_setting_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import extension_setting_specifics_pb2 as components_dot_sync_dot_protocol_dot_extension__setting__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4components/sync/protocol/app_setting_specifics.proto\x12\x07sync_pb\x1a:components/sync/protocol/extension_setting_specifics.proto\"f\n\x13\x41ppSettingSpecifics\x12O\n\x11\x65xtension_setting\x18\x01 \x01(\x0b\x32\".sync_pb.ExtensionSettingSpecificsR\x10\x65xtensionSettingBa\n\x0b\x63om.sync_pbB\x18\x41ppSettingSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.app_setting_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\030AppSettingSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_APPSETTINGSPECIFICS']._serialized_start=125
  _globals['_APPSETTINGSPECIFICS']._serialized_end=227
# @@protoc_insertion_point(module_scope)
