# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/arc_package_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/arc_package_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4components/sync/protocol/arc_package_specifics.proto\x12\x07sync_pb\"\xc0\x01\n\x13\x41rcPackageSpecifics\x12!\n\x0cpackage_name\x18\x01 \x01(\tR\x0bpackageName\x12\'\n\x0fpackage_version\x18\x02 \x01(\x05R\x0epackageVersion\x12\x33\n\x16last_backup_android_id\x18\x03 \x01(\x03R\x13lastBackupAndroidId\x12(\n\x10last_backup_time\x18\x04 \x01(\x03R\x0elastBackupTimeBa\n\x0b\x63om.sync_pbB\x18\x41rcPackageSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.arc_package_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\030ArcPackageSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_ARCPACKAGESPECIFICS']._serialized_start=66
  _globals['_ARCPACKAGESPECIFICS']._serialized_end=258
# @@protoc_insertion_point(module_scope)
