# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_valuable_setting_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/autofill_valuable_setting_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBcomponents/sync/protocol/autofill_valuable_setting_specifics.proto\x12\x07sync_pb\"\xa4\x01\n AutofillValuableSettingSpecifics\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n\nbool_value\x18\x02 \x01(\x08H\x00R\tboolValue\x12#\n\x0cstring_value\x18\x03 \x01(\tH\x00R\x0bstringValue\x12\x1d\n\tint_value\x18\x04 \x01(\x03H\x00R\x08intValueB\x07\n\x05ValueBn\n\x0b\x63om.sync_pbB%AutofillValuableSettingSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_valuable_setting_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB%AutofillValuableSettingSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_AUTOFILLVALUABLESETTINGSPECIFICS']._serialized_start=80
  _globals['_AUTOFILLVALUABLESETTINGSPECIFICS']._serialized_end=244
# @@protoc_insertion_point(module_scope)
