# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_wallet_credential_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/autofill_wallet_credential_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCcomponents/sync/protocol/autofill_wallet_credential_specifics.proto\x12\x07sync_pb\"\xa7\x01\n!AutofillWalletCredentialSpecifics\x12#\n\rinstrument_id\x18\x01 \x01(\tR\x0cinstrumentId\x12\x10\n\x03\x63vc\x18\x02 \x01(\tR\x03\x63vc\x12K\n#last_updated_time_unix_epoch_millis\x18\x03 \x01(\x03R\x1elastUpdatedTimeUnixEpochMillisBo\n\x0b\x63om.sync_pbB&AutofillWalletCredentialSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_wallet_credential_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB&AutofillWalletCredentialSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_AUTOFILLWALLETCREDENTIALSPECIFICS']._serialized_start=81
  _globals['_AUTOFILLWALLETCREDENTIALSPECIFICS']._serialized_end=248
# @@protoc_insertion_point(module_scope)
