# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_wallet_usage_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/autofill_wallet_usage_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>components/sync/protocol/autofill_wallet_usage_specifics.proto\x12\x07sync_pb\"\x82\x03\n\x1c\x41utofillWalletUsageSpecifics\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12s\n\x17virtual_card_usage_data\x18\x02 \x01(\x0b\x32:.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageDataH\x00R\x14virtualCardUsageData\x1a\xc5\x01\n\x14VirtualCardUsageData\x12#\n\rinstrument_id\x18\x01 \x01(\x03R\x0cinstrumentId\x12\x33\n\x16virtual_card_last_four\x18\x02 \x01(\tR\x13virtualCardLastFour\x12!\n\x0cmerchant_url\x18\x03 \x01(\tR\x0bmerchantUrl\x12\x30\n\x14merchant_app_package\x18\x04 \x01(\tR\x12merchantAppPackageB\x11\n\x0fusage_data_typeBj\n\x0b\x63om.sync_pbB!AutofillWalletUsageSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_wallet_usage_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB!AutofillWalletUsageSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_AUTOFILLWALLETUSAGESPECIFICS']._serialized_start=76
  _globals['_AUTOFILLWALLETUSAGESPECIFICS']._serialized_end=462
  _globals['_AUTOFILLWALLETUSAGESPECIFICS_VIRTUALCARDUSAGEDATA']._serialized_start=246
  _globals['_AUTOFILLWALLETUSAGESPECIFICS_VIRTUALCARDUSAGEDATA']._serialized_end=443
# @@protoc_insertion_point(module_scope)
