# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/bookmark_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/bookmark_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1components/sync/protocol/bookmark_specifics.proto\x12\x07sync_pb\x1a.components/sync/protocol/unique_position.proto\"2\n\x08MetaInfo\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"\xb4\x04\n\x11\x42ookmarkSpecifics\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n\x07\x66\x61vicon\x18\x02 \x01(\x0cR\x07\x66\x61vicon\x12<\n\x1alegacy_canonicalized_title\x18\x03 \x01(\tR\x18legacyCanonicalizedTitle\x12(\n\x10\x63reation_time_us\x18\x04 \x01(\x03R\x0e\x63reationTimeUs\x12\x19\n\x08icon_url\x18\x05 \x01(\tR\x07iconUrl\x12.\n\tmeta_info\x18\x06 \x03(\x0b\x32\x11.sync_pb.MetaInfoR\x08metaInfo\x12\x12\n\x04guid\x18\n \x01(\tR\x04guid\x12\x1d\n\nfull_title\x18\x0b \x01(\tR\tfullTitle\x12\x1f\n\x0bparent_guid\x18\x0e \x01(\tR\nparentGuid\x12\x33\n\x04type\x18\x0f \x01(\x0e\x32\x1f.sync_pb.BookmarkSpecifics.TypeR\x04type\x12@\n\x0funique_position\x18\x10 \x01(\x0b\x32\x17.sync_pb.UniquePositionR\x0euniquePosition\x12)\n\x11last_used_time_us\x18\x11 \x01(\x03R\x0elastUsedTimeUs\",\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03URL\x10\x01\x12\n\n\x06\x46OLDER\x10\x02J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\x0c\x10\rJ\x04\x08\r\x10\x0e\x42_\n\x0b\x63om.sync_pbB\x16\x42ookmarkSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.bookmark_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\026BookmarkSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_METAINFO']._serialized_start=110
  _globals['_METAINFO']._serialized_end=160
  _globals['_BOOKMARKSPECIFICS']._serialized_start=163
  _globals['_BOOKMARKSPECIFICS']._serialized_end=727
  _globals['_BOOKMARKSPECIFICS_TYPE']._serialized_start=653
  _globals['_BOOKMARKSPECIFICS_TYPE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
