# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/bookmark_model_metadata.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/bookmark_model_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import data_type_state_pb2 as components_dot_sync_dot_protocol_dot_data__type__state__pb2
from components.sync.protocol import entity_metadata_pb2 as components_dot_sync_dot_protocol_dot_entity__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6components/sync/protocol/bookmark_model_metadata.proto\x12\x07sync_pb\x1a.components/sync/protocol/data_type_state.proto\x1a.components/sync/protocol/entity_metadata.proto\"W\n\x10\x42ookmarkMetadata\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x33\n\x08metadata\x18\x02 \x01(\x0b\x32\x17.sync_pb.EntityMetadataR\x08metadata\"\xb6\x04\n\x15\x42ookmarkModelMetadata\x12>\n\x0f\x64\x61ta_type_state\x18\x01 \x01(\x0b\x32\x16.sync_pb.DataTypeStateR\rdataTypeState\x12H\n\x12\x62ookmarks_metadata\x18\x02 \x03(\x0b\x32\x19.sync_pb.BookmarkMetadataR\x11\x62ookmarksMetadata\x12Q\n%bookmarks_hierarchy_fields_reuploaded\x18\x06 \x01(\x08R\"bookmarksHierarchyFieldsReuploaded\x12V\n)num_ignored_updates_due_to_missing_parent\x18\x07 \x01(\x03R#numIgnoredUpdatesDueToMissingParent\x12p\n7max_version_among_ignored_updates_due_to_missing_parent\x18\x08 \x01(\x03R/maxVersionAmongIgnoredUpdatesDueToMissingParent\x12\x64\n0last_initial_merge_remote_updates_exceeded_limit\x18\t \x01(\x08R*lastInitialMergeRemoteUpdatesExceededLimitJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06\x42\x63\n\x0b\x63om.sync_pbB\x1a\x42ookmarkModelMetadataProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.bookmark_model_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\032BookmarkModelMetadataProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_BOOKMARKMETADATA']._serialized_start=163
  _globals['_BOOKMARKMETADATA']._serialized_end=250
  _globals['_BOOKMARKMODELMETADATA']._serialized_start=253
  _globals['_BOOKMARKMODELMETADATA']._serialized_end=819
# @@protoc_insertion_point(module_scope)
