# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/client_commands.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/client_commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/client_commands.proto\x12\x07sync_pb\"N\n\x10\x43ustomNudgeDelay\x12\x1f\n\x0b\x64\x61tatype_id\x18\x01 \x01(\x05R\ndatatypeId\x12\x19\n\x08\x64\x65lay_ms\x18\x02 \x01(\x05R\x07\x64\x65layMs\"\xce\x05\n\rClientCommand\x12\x33\n\x16set_sync_poll_interval\x18\x01 \x01(\x05R\x13setSyncPollInterval\x12@\n\x1bset_sync_long_poll_interval\x18\x02 \x01(\x05\x42\x02\x18\x01R\x17setSyncLongPollInterval\x12\x31\n\x15max_commit_batch_size\x18\x03 \x01(\x05R\x12maxCommitBatchSize\x12\x34\n\x16throttle_delay_seconds\x18\x05 \x01(\x05R\x14throttleDelaySeconds\x12R\n$client_invalidation_hint_buffer_size\x18\x06 \x01(\x05\x42\x02\x18\x01R clientInvalidationHintBufferSize\x12I\n\x13\x63ustom_nudge_delays\x18\x08 \x03(\x0b\x32\x19.sync_pb.CustomNudgeDelayR\x11\x63ustomNudgeDelays\x12;\n\x1a\x65xtension_types_max_tokens\x18\t \x01(\x05R\x17\x65xtensionTypesMaxTokens\x12T\n\'extension_types_refill_interval_seconds\x18\n \x01(\x05R#extensionTypesRefillIntervalSeconds\x12h\n2extension_types_depleted_quota_nudge_delay_seconds\x18\x0b \x01(\x05R,extensionTypesDepletedQuotaNudgeDelaySecondsJ\x04\x08\x04\x10\x05J\x04\x08\x07\x10\x08R\x1dsessions_commit_delay_secondsR\x16gu_retry_delay_secondsB\\\n\x0b\x63om.sync_pbB\x13\x43lientCommandsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.client_commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\023ClientCommandsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_CLIENTCOMMAND'].fields_by_name['set_sync_long_poll_interval']._loaded_options = None
  _globals['_CLIENTCOMMAND'].fields_by_name['set_sync_long_poll_interval']._serialized_options = b'\030\001'
  _globals['_CLIENTCOMMAND'].fields_by_name['client_invalidation_hint_buffer_size']._loaded_options = None
  _globals['_CLIENTCOMMAND'].fields_by_name['client_invalidation_hint_buffer_size']._serialized_options = b'\030\001'
  _globals['_CUSTOMNUDGEDELAY']._serialized_start=59
  _globals['_CUSTOMNUDGEDELAY']._serialized_end=137
  _globals['_CLIENTCOMMAND']._serialized_start=140
  _globals['_CLIENTCOMMAND']._serialized_end=858
# @@protoc_insertion_point(module_scope)
