# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/deletion_origin.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/deletion_origin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/deletion_origin.proto\x12\x07sync_pb\"\xf9\x02\n\x0e\x44\x65letionOrigin\x12)\n\x10\x63hromium_version\x18\x01 \x01(\tR\x0f\x63hromiumVersion\x12O\n%google_play_services_apk_version_name\x18\x02 \x01(\tR googlePlayServicesApkVersionName\x12$\n\x0e\x66ile_name_hash\x18\x03 \x01(\x07R\x0c\x66ileNameHash\x12(\n\x10\x66ile_line_number\x18\x04 \x01(\x05R\x0e\x66ileLineNumber\x12?\n\x1c\x66ile_name_possibly_truncated\x18\x05 \x01(\tR\x19\x66ileNamePossiblyTruncated\x12Z\n+unique_source_tag_no_pii_possibly_truncated\x18\x06 \x01(\tR%uniqueSourceTagNoPiiPossiblyTruncatedB\\\n\x0b\x63om.sync_pbB\x13\x44\x65letionOriginProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.deletion_origin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\023DeletionOriginProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_DELETIONORIGIN']._serialized_start=60
  _globals['_DELETIONORIGIN']._serialized_end=437
# @@protoc_insertion_point(module_scope)
