# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/extension_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/extension_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2components/sync/protocol/extension_specifics.proto\x12\x07sync_pb\"\xa6\x03\n\x12\x45xtensionSpecifics\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12\x1d\n\nupdate_url\x18\x03 \x01(\tR\tupdateUrl\x12\x18\n\x07\x65nabled\x18\x04 \x01(\x08R\x07\x65nabled\x12+\n\x11incognito_enabled\x18\x05 \x01(\x08R\x10incognitoEnabled\x12\x16\n\x04name\x18\x06 \x01(\tB\x02\x18\x01R\x04name\x12%\n\x0eremote_install\x18\x07 \x01(\x08R\rremoteInstall\x12\x38\n\x16installed_by_custodian\x18\x08 \x01(\x08\x42\x02\x18\x01R\x14installedByCustodian\x12,\n\x10\x61ll_urls_enabled\x18\t \x01(\x08\x42\x02\x18\x01R\x0e\x61llUrlsEnabled\x12\'\n\x0f\x64isable_reasons\x18\n \x01(\x05R\x0e\x64isableReasons\x12\x30\n\x14\x64isable_reasons_list\x18\x0b \x03(\x05R\x12\x64isableReasonsListB`\n\x0b\x63om.sync_pbB\x17\x45xtensionSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.extension_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\027ExtensionSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_EXTENSIONSPECIFICS'].fields_by_name['name']._loaded_options = None
  _globals['_EXTENSIONSPECIFICS'].fields_by_name['name']._serialized_options = b'\030\001'
  _globals['_EXTENSIONSPECIFICS'].fields_by_name['installed_by_custodian']._loaded_options = None
  _globals['_EXTENSIONSPECIFICS'].fields_by_name['installed_by_custodian']._serialized_options = b'\030\001'
  _globals['_EXTENSIONSPECIFICS'].fields_by_name['all_urls_enabled']._loaded_options = None
  _globals['_EXTENSIONSPECIFICS'].fields_by_name['all_urls_enabled']._serialized_options = b'\030\001'
  _globals['_EXTENSIONSPECIFICS']._serialized_start=64
  _globals['_EXTENSIONSPECIFICS']._serialized_end=486
# @@protoc_insertion_point(module_scope)
