# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/history_status.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/history_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-components/sync/protocol/history_status.proto\x12\x07sync_pb\"\x16\n\x14HistoryStatusRequest\"\x82\x01\n\x15HistoryStatusResponse\x12?\n\x19min_poll_interval_seconds\x18\x01 \x01(\x05:\x04\x33\x36\x30\x30R\x16minPollIntervalSeconds\x12(\n\x10has_derived_data\x18\x02 \x01(\x08R\x0ehasDerivedDataB[\n\x0b\x63om.sync_pbB\x12HistoryStatusProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.history_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\022HistoryStatusProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_HISTORYSTATUSREQUEST']._serialized_start=58
  _globals['_HISTORYSTATUSREQUEST']._serialized_end=80
  _globals['_HISTORYSTATUSRESPONSE']._serialized_start=83
  _globals['_HISTORYSTATUSRESPONSE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
