# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/history_delete_directive_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/history_delete_directive_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAcomponents/sync/protocol/history_delete_directive_specifics.proto\x12\x07sync_pb\"\x90\x02\n\x1fHistoryDeleteDirectiveSpecifics\x12L\n\x13global_id_directive\x18\x01 \x01(\x0b\x32\x1a.sync_pb.GlobalIdDirectiveH\x00R\x11globalIdDirective\x12O\n\x14time_range_directive\x18\x02 \x01(\x0b\x32\x1b.sync_pb.TimeRangeDirectiveH\x00R\x12timeRangeDirective\x12<\n\rurl_directive\x18\x03 \x01(\x0b\x32\x15.sync_pb.UrlDirectiveH\x00R\x0curlDirectiveB\x10\n\x0e\x64irective_type\"|\n\x11GlobalIdDirective\x12\x1b\n\tglobal_id\x18\x01 \x03(\x03R\x08globalId\x12&\n\x0fstart_time_usec\x18\x02 \x01(\x03R\rstartTimeUsec\x12\"\n\rend_time_usec\x18\x03 \x01(\x03R\x0b\x65ndTimeUsec\"w\n\x12TimeRangeDirective\x12&\n\x0fstart_time_usec\x18\x01 \x01(\x03R\rstartTimeUsec\x12\"\n\rend_time_usec\x18\x02 \x01(\x03R\x0b\x65ndTimeUsec\x12\x15\n\x06\x61pp_id\x18\x03 \x01(\tR\x05\x61ppId\"[\n\x0cUrlDirective\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\"\n\rend_time_usec\x18\x02 \x01(\x03R\x0b\x65ndTimeUsec\x12\x15\n\x06\x61pp_id\x18\x03 \x01(\tR\x05\x61ppIdBm\n\x0b\x63om.sync_pbB$HistoryDeleteDirectiveSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.history_delete_directive_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB$HistoryDeleteDirectiveSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_HISTORYDELETEDIRECTIVESPECIFICS']._serialized_start=79
  _globals['_HISTORYDELETEDIRECTIVESPECIFICS']._serialized_end=351
  _globals['_GLOBALIDDIRECTIVE']._serialized_start=353
  _globals['_GLOBALIDDIRECTIVE']._serialized_end=477
  _globals['_TIMERANGEDIRECTIVE']._serialized_start=479
  _globals['_TIMERANGEDIRECTIVE']._serialized_end=598
  _globals['_URLDIRECTIVE']._serialized_start=600
  _globals['_URLDIRECTIVE']._serialized_end=691
# @@protoc_insertion_point(module_scope)
