# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/loopback_server.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/loopback_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import sync_entity_pb2 as components_dot_sync_dot_protocol_dot_sync__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/loopback_server.proto\x12\x07sync_pb\x1a*components/sync/protocol/sync_entity.proto\"\xe5\x01\n\x14LoopbackServerEntity\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32\".sync_pb.LoopbackServerEntity.TypeR\x04type\x12+\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x13.sync_pb.SyncEntityR\x06\x65ntity\x12\x1b\n\tdata_type\x18\x03 \x01(\x03R\x08\x64\x61taType\"K\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x42OOKMARK\x10\x01\x12\r\n\tPERMANENT\x10\x02\x12\r\n\tTOMBSTONE\x10\x03\x12\n\n\x06UNIQUE\x10\x04\"\xea\x01\n\x13LoopbackServerProto\x12\x18\n\x07version\x18\x01 \x01(\x03R\x07version\x12%\n\x0estore_birthday\x18\x02 \x01(\x03R\rstoreBirthday\x12\x39\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x1d.sync_pb.LoopbackServerEntityR\x08\x65ntities\x12#\n\rkeystore_keys\x18\x04 \x03(\x0cR\x0ckeystoreKeys\x12\x32\n\x15last_version_assigned\x18\x05 \x01(\x03R\x13lastVersionAssignedB\\\n\x0b\x63om.sync_pbB\x13LoopbackServerProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.loopback_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\023LoopbackServerProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_LOOPBACKSERVERENTITY']._serialized_start=104
  _globals['_LOOPBACKSERVERENTITY']._serialized_end=333
  _globals['_LOOPBACKSERVERENTITY_TYPE']._serialized_start=258
  _globals['_LOOPBACKSERVERENTITY_TYPE']._serialized_end=333
  _globals['_LOOPBACKSERVERPROTO']._serialized_start=336
  _globals['_LOOPBACKSERVERPROTO']._serialized_end=570
# @@protoc_insertion_point(module_scope)
