# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/note_entity.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/note_entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*components/sync/protocol/note_entity.proto\x12\x07sync_pb\"\xfc\x01\n\nNoteEntity\x12\x1d\n\nplain_text\x18\x01 \x01(\tR\tplainText\x12\x1b\n\trich_text\x18\x02 \x01(\tR\x08richText\x12?\n\x0btarget_type\x18\x03 \x01(\x0e\x32\x1e.sync_pb.NoteEntity.TargetTypeR\ntargetType\x12\x30\n\x14\x63urrent_note_version\x18\x04 \x01(\x05R\x12\x63urrentNoteVersion\"?\n\nTargetType\x12\x1b\n\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10TARGET_TYPE_PAGE\x10\x01\x42X\n\x0b\x63om.sync_pbB\x0fNoteEntityProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.note_entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\017NoteEntityProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_NOTEENTITY']._serialized_start=56
  _globals['_NOTEENTITY']._serialized_end=308
  _globals['_NOTEENTITY_TARGETTYPE']._serialized_start=245
  _globals['_NOTEENTITY_TARGETTYPE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
