# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/password_sharing_recipients.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/password_sharing_recipients.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import password_sharing_invitation_specifics_pb2 as components_dot_sync_dot_protocol_dot_password__sharing__invitation__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:components/sync/protocol/password_sharing_recipients.proto\x12\x07sync_pb\x1a\x44\x63omponents/sync/protocol/password_sharing_invitation_specifics.proto\"\"\n PasswordSharingRecipientsRequest\"\x8e\x02\n!PasswordSharingRecipientsResponse\x12\x62\n\x06result\x18\x01 \x01(\x0e\x32J.sync_pb.PasswordSharingRecipientsResponse.PasswordSharingRecipientsResultR\x06result\x12\x31\n\nrecipients\x18\x02 \x03(\x0b\x32\x11.sync_pb.UserInfoR\nrecipients\"R\n\x1fPasswordSharingRecipientsResult\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x15\n\x11NOT_FAMILY_MEMBER\x10\x02\x42g\n\x0b\x63om.sync_pbB\x1ePasswordSharingRecipientsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.password_sharing_recipients_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\036PasswordSharingRecipientsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_PASSWORDSHARINGRECIPIENTSREQUEST']._serialized_start=141
  _globals['_PASSWORDSHARINGRECIPIENTSREQUEST']._serialized_end=175
  _globals['_PASSWORDSHARINGRECIPIENTSRESPONSE']._serialized_start=178
  _globals['_PASSWORDSHARINGRECIPIENTSRESPONSE']._serialized_end=448
  _globals['_PASSWORDSHARINGRECIPIENTSRESPONSE_PASSWORDSHARINGRECIPIENTSRESULT']._serialized_start=366
  _globals['_PASSWORDSHARINGRECIPIENTSRESPONSE_PASSWORDSHARINGRECIPIENTSRESULT']._serialized_end=448
# @@protoc_insertion_point(module_scope)
