# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/persisted_entity_data.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/persisted_entity_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import entity_specifics_pb2 as components_dot_sync_dot_protocol_dot_entity__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4components/sync/protocol/persisted_entity_data.proto\x12\x07sync_pb\x1a/components/sync/protocol/entity_specifics.proto\"a\n\x13PersistedEntityData\x12\x12\n\x04name\x18\x08 \x01(\tR\x04name\x12\x36\n\tspecifics\x18\x15 \x01(\x0b\x32\x18.sync_pb.EntitySpecificsR\tspecificsBa\n\x0b\x63om.sync_pbB\x18PersistedEntityDataProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.persisted_entity_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\030PersistedEntityDataProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_PERSISTEDENTITYDATA']._serialized_start=114
  _globals['_PERSISTEDENTITYDATA']._serialized_end=211
# @@protoc_insertion_point(module_scope)
