# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/plus_address_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/plus_address_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5components/sync/protocol/plus_address_specifics.proto\x12\x07sync_pb\"~\n\x14PlusAddressSpecifics\x12\x1d\n\nprofile_id\x18\x01 \x01(\tR\tprofileId\x12\x14\n\x05\x66\x61\x63\x65t\x18\x02 \x01(\tR\x05\x66\x61\x63\x65t\x12\x31\n\nplus_email\x18\x03 \x01(\x0b\x32\x12.sync_pb.PlusEmailR\tplusEmail\"0\n\tPlusEmail\x12#\n\remail_address\x18\x01 \x01(\tR\x0c\x65mailAddressBb\n\x0b\x63om.sync_pbB\x19PlusAddressSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.plus_address_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\031PlusAddressSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_PLUSADDRESSSPECIFICS']._serialized_start=66
  _globals['_PLUSADDRESSSPECIFICS']._serialized_end=192
  _globals['_PLUSEMAIL']._serialized_start=194
  _globals['_PLUSEMAIL']._serialized_end=242
# @@protoc_insertion_point(module_scope)
