# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/power_bookmark_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/power_bookmark_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import note_entity_pb2 as components_dot_sync_dot_protocol_dot_note__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7components/sync/protocol/power_bookmark_specifics.proto\x12\x07sync_pb\x1a*components/sync/protocol/note_entity.proto\"O\n\x0bPowerEntity\x12\x36\n\x0bnote_entity\x18\x02 \x01(\x0b\x32\x13.sync_pb.NoteEntityH\x00R\nnoteEntityB\x08\n\x06\x65ntity\"\xec\x02\n\x16PowerBookmarkSpecifics\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12H\n\npower_type\x18\x03 \x01(\x0e\x32).sync_pb.PowerBookmarkSpecifics.PowerTypeR\tpowerType\x12,\n\x12\x63reation_time_usec\x18\x04 \x01(\x03R\x10\x63reationTimeUsec\x12(\n\x10update_time_usec\x18\x05 \x01(\x03R\x0eupdateTimeUsec\x12\x37\n\x0cpower_entity\x18\x64 \x01(\x0b\x32\x14.sync_pb.PowerEntityR\x0bpowerEntity\"Q\n\tPowerType\x12\x1a\n\x16POWER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fPOWER_TYPE_MOCK\x10\x01\x12\x13\n\x0fPOWER_TYPE_NOTE\x10\x02\x42\x64\n\x0b\x63om.sync_pbB\x1bPowerBookmarkSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.power_bookmark_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\033PowerBookmarkSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_POWERENTITY']._serialized_start=112
  _globals['_POWERENTITY']._serialized_end=191
  _globals['_POWERBOOKMARKSPECIFICS']._serialized_start=194
  _globals['_POWERBOOKMARKSPECIFICS']._serialized_end=558
  _globals['_POWERBOOKMARKSPECIFICS_POWERTYPE']._serialized_start=477
  _globals['_POWERBOOKMARKSPECIFICS_POWERTYPE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
