# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/printer_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/printer_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0components/sync/protocol/printer_specifics.proto\x12\x07sync_pb\"\x8c\x02\n\x13PrinterPPDReference\x12\x31\n\x15user_supplied_ppd_url\x18\x01 \x01(\tR\x12userSuppliedPpdUrl\x12\x39\n\x16\x65\x66\x66\x65\x63tive_manufacturer\x18\x02 \x01(\tB\x02\x18\x01R\x15\x65\x66\x66\x65\x63tiveManufacturer\x12+\n\x0f\x65\x66\x66\x65\x63tive_model\x18\x03 \x01(\tB\x02\x18\x01R\x0e\x65\x66\x66\x65\x63tiveModel\x12\x37\n\x18\x65\x66\x66\x65\x63tive_make_and_model\x18\x04 \x01(\tR\x15\x65\x66\x66\x65\x63tiveMakeAndModel\x12!\n\x08\x61utoconf\x18\x05 \x01(\x08:\x05\x66\x61lseR\x08\x61utoconf\"\xa5\x03\n\x10PrinterSpecifics\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12!\n\x0c\x64isplay_name\x18\x02 \x01(\tR\x0b\x64isplayName\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12&\n\x0cmanufacturer\x18\x04 \x01(\tB\x02\x18\x01R\x0cmanufacturer\x12\x18\n\x05model\x18\x05 \x01(\tB\x02\x18\x01R\x05model\x12\x10\n\x03uri\x18\x06 \x01(\tR\x03uri\x12\x12\n\x04uuid\x18\x07 \x01(\tR\x04uuid\x12\x14\n\x03ppd\x18\x08 \x01(\x0c\x42\x02\x18\x01R\x03ppd\x12\x41\n\rppd_reference\x18\t \x01(\x0b\x32\x1c.sync_pb.PrinterPPDReferenceR\x0cppdReference\x12+\n\x11updated_timestamp\x18\n \x01(\x03R\x10updatedTimestamp\x12$\n\x0emake_and_model\x18\x0b \x01(\tR\x0cmakeAndModel\x12(\n\x10print_server_uri\x18\x0c \x01(\tR\x0eprintServerUriB^\n\x0b\x63om.sync_pbB\x15PrinterSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.printer_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\025PrinterSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_manufacturer']._loaded_options = None
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_manufacturer']._serialized_options = b'\030\001'
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_model']._loaded_options = None
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_model']._serialized_options = b'\030\001'
  _globals['_PRINTERSPECIFICS'].fields_by_name['manufacturer']._loaded_options = None
  _globals['_PRINTERSPECIFICS'].fields_by_name['manufacturer']._serialized_options = b'\030\001'
  _globals['_PRINTERSPECIFICS'].fields_by_name['model']._loaded_options = None
  _globals['_PRINTERSPECIFICS'].fields_by_name['model']._serialized_options = b'\030\001'
  _globals['_PRINTERSPECIFICS'].fields_by_name['ppd']._loaded_options = None
  _globals['_PRINTERSPECIFICS'].fields_by_name['ppd']._serialized_options = b'\030\001'
  _globals['_PRINTERPPDREFERENCE']._serialized_start=62
  _globals['_PRINTERPPDREFERENCE']._serialized_end=330
  _globals['_PRINTERSPECIFICS']._serialized_start=333
  _globals['_PRINTERSPECIFICS']._serialized_end=754
# @@protoc_insertion_point(module_scope)
