# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/product_comparison_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/product_comparison_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;components/sync/protocol/product_comparison_specifics.proto\x12\x07sync_pb\x1a.components/sync/protocol/unique_position.proto\"\xaa\x03\n\x1aProductComparisonSpecifics\x12\x12\n\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x44\n\x1f\x63reation_time_unix_epoch_millis\x18\x02 \x01(\x03R\x1b\x63reationTimeUnixEpochMillis\x12@\n\x1dupdate_time_unix_epoch_millis\x18\x03 \x01(\x03R\x19updateTimeUnixEpochMillis\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\x12+\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x17.sync_pb.ComparisonDataR\x04\x64\x61ta\x12K\n\x12product_comparison\x18\x06 \x01(\x0b\x32\x1a.sync_pb.ProductComparisonH\x00R\x11productComparison\x12X\n\x17product_comparison_item\x18\x07 \x01(\x0b\x32\x1e.sync_pb.ProductComparisonItemH\x00R\x15productComparisonItemB\x08\n\x06\x65ntity\"\"\n\x0e\x43omparisonData\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\"\'\n\x11ProductComparison\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"\xb9\x01\n\x15ProductComparisonItem\x12\x36\n\x17product_comparison_uuid\x18\x01 \x01(\tR\x15productComparisonUuid\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12@\n\x0funique_position\x18\x03 \x01(\x0b\x32\x17.sync_pb.UniquePositionR\x0euniquePosition\x12\x14\n\x05title\x18\x04 \x01(\tR\x05titleBh\n\x0b\x63om.sync_pbB\x1fProductComparisonSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.product_comparison_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\037ProductComparisonSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_PRODUCTCOMPARISONSPECIFICS']._serialized_start=121
  _globals['_PRODUCTCOMPARISONSPECIFICS']._serialized_end=547
  _globals['_COMPARISONDATA']._serialized_start=549
  _globals['_COMPARISONDATA']._serialized_end=583
  _globals['_PRODUCTCOMPARISON']._serialized_start=585
  _globals['_PRODUCTCOMPARISON']._serialized_end=624
  _globals['_PRODUCTCOMPARISONITEM']._serialized_start=627
  _globals['_PRODUCTCOMPARISONITEM']._serialized_end=812
# @@protoc_insertion_point(module_scope)
