# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/reading_list_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/reading_list_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5components/sync/protocol/reading_list_specifics.proto\x12\x07sync_pb\"\xd0\x03\n\x14ReadingListSpecifics\x12\x19\n\x08\x65ntry_id\x18\x01 \x01(\tR\x07\x65ntryId\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n\x03url\x18\x03 \x01(\tR\x03url\x12(\n\x10\x63reation_time_us\x18\x04 \x01(\x03R\x0e\x63reationTimeUs\x12$\n\x0eupdate_time_us\x18\x05 \x01(\x03R\x0cupdateTimeUs\x12+\n\x12\x66irst_read_time_us\x18\x07 \x01(\x03R\x0f\x66irstReadTimeUs\x12/\n\x14update_title_time_us\x18\x08 \x01(\x03R\x11updateTitleTimeUs\x12=\n\x1b\x65stimated_read_time_seconds\x18\t \x01(\x05R\x18\x65stimatedReadTimeSeconds\x12L\n\x06status\x18\x06 \x01(\x0e\x32\x34.sync_pb.ReadingListSpecifics.ReadingListEntryStatusR\x06status\":\n\x16ReadingListEntryStatus\x12\n\n\x06UNREAD\x10\x00\x12\x08\n\x04READ\x10\x01\x12\n\n\x06UNSEEN\x10\x02\x42\x62\n\x0b\x63om.sync_pbB\x19ReadingListSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.reading_list_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\031ReadingListSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_READINGLISTSPECIFICS']._serialized_start=67
  _globals['_READINGLISTSPECIFICS']._serialized_end=531
  _globals['_READINGLISTSPECIFICS_READINGLISTENTRYSTATUS']._serialized_start=473
  _globals['_READINGLISTSPECIFICS_READINGLISTENTRYSTATUS']._serialized_end=531
# @@protoc_insertion_point(module_scope)
