# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/security_event_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/security_event_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import gaia_password_reuse_pb2 as components_dot_sync_dot_protocol_dot_gaia__password__reuse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7components/sync/protocol/security_event_specifics.proto\x12\x07sync_pb\x1a\x32\x63omponents/sync/protocol/gaia_password_reuse.proto\"\xa2\x01\n\x16SecurityEventSpecifics\x12W\n\x19gaia_password_reuse_event\x18\x01 \x01(\x0b\x32\x1a.sync_pb.GaiaPasswordReuseH\x00R\x16gaiaPasswordReuseEvent\x12&\n\x0f\x65vent_time_usec\x18\x02 \x01(\x03R\reventTimeUsecB\x07\n\x05\x65ventBd\n\x0b\x63om.sync_pbB\x1bSecurityEventSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.security_event_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\033SecurityEventSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_SECURITYEVENTSPECIFICS']._serialized_start=121
  _globals['_SECURITYEVENTSPECIFICS']._serialized_end=283
# @@protoc_insertion_point(module_scope)
