# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/send_tab_to_self_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/send_tab_to_self_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9components/sync/protocol/send_tab_to_self_specifics.proto\x12\x07sync_pb\"\xcc\x02\n\x16SendTabToSelfSpecifics\x12\x12\n\x04guid\x18\x05 \x01(\tR\x04guid\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12(\n\x10shared_time_usec\x18\x03 \x01(\x03R\x0esharedTimeUsec\x12\x1f\n\x0b\x64\x65vice_name\x18\x04 \x01(\tR\ndeviceName\x12@\n\x1dtarget_device_sync_cache_guid\x18\x07 \x01(\tR\x19targetDeviceSyncCacheGuid\x12\x16\n\x06opened\x18\x08 \x01(\x08R\x06opened\x12\x35\n\x16notification_dismissed\x18\t \x01(\x08R\x15notificationDismissedJ\x04\x08\x06\x10\x07R\x14navigation_time_usecBd\n\x0b\x63om.sync_pbB\x1bSendTabToSelfSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.send_tab_to_self_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\033SendTabToSelfSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_SENDTABTOSELFSPECIFICS']._serialized_start=71
  _globals['_SENDTABTOSELFSPECIFICS']._serialized_end=403
# @@protoc_insertion_point(module_scope)
