# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/shared_tab_group_account_data_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/shared_tab_group_account_data_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcomponents/sync/protocol/shared_tab_group_account_data_specifics.proto\x12\x07sync_pb\"\xf5\x02\n\"SharedTabGroupAccountDataSpecifics\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12)\n\x10\x63ollaboration_id\x18\x02 \x01(\tR\x0f\x63ollaborationId\x12I\n\x12shared_tab_details\x18\x03 \x01(\x0b\x32\x19.sync_pb.SharedTabDetailsH\x00R\x10sharedTabDetails\x12Y\n\x18shared_tab_group_details\x18\x04 \x01(\x0b\x32\x1e.sync_pb.SharedTabGroupDetailsH\x00R\x15sharedTabGroupDetails\x12\x46\n update_time_windows_epoch_micros\x18\x05 \x01(\x03R\x1cupdateTimeWindowsEpochMicros\x12\x18\n\x07version\x18\x06 \x01(\x05R\x07versionB\x08\n\x06\x65ntity\"\x8f\x01\n\x10SharedTabDetails\x12\x31\n\x15shared_tab_group_guid\x18\x01 \x01(\tR\x12sharedTabGroupGuid\x12H\n!last_seen_timestamp_windows_epoch\x18\x02 \x01(\x03R\x1dlastSeenTimestampWindowsEpoch\"@\n\x15SharedTabGroupDetails\x12\'\n\x0fpinned_position\x18\x01 \x01(\x03R\x0epinnedPositionBp\n\x0b\x63om.sync_pbB\'SharedTabGroupAccountDataSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.shared_tab_group_account_data_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\'SharedTabGroupAccountDataSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_SHAREDTABGROUPACCOUNTDATASPECIFICS']._serialized_start=84
  _globals['_SHAREDTABGROUPACCOUNTDATASPECIFICS']._serialized_end=457
  _globals['_SHAREDTABDETAILS']._serialized_start=460
  _globals['_SHAREDTABDETAILS']._serialized_end=603
  _globals['_SHAREDTABGROUPDETAILS']._serialized_start=605
  _globals['_SHAREDTABGROUPDETAILS']._serialized_end=669
# @@protoc_insertion_point(module_scope)
