# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/shared_tab_group_data_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/shared_tab_group_data_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>components/sync/protocol/shared_tab_group_data_specifics.proto\x12\x07sync_pb\x1a.components/sync/protocol/unique_position.proto\"\x83\x02\n\x1bSharedTabGroupDataSpecifics\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12\x36\n\ttab_group\x18\x03 \x01(\x0b\x32\x17.sync_pb.SharedTabGroupH\x00R\x08tabGroup\x12&\n\x03tab\x18\x04 \x01(\x0b\x32\x12.sync_pb.SharedTabH\x00R\x03tab\x12\x46\n update_time_windows_epoch_micros\x18\x05 \x01(\x03R\x1cupdateTimeWindowsEpochMicros\x12\x18\n\x07version\x18\x06 \x01(\x05R\x07versionB\x08\n\x06\x65ntityJ\x04\x08\x02\x10\x03\"\x92\x02\n\x0eSharedTabGroup\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x33\n\x05\x63olor\x18\x02 \x01(\x0e\x32\x1d.sync_pb.SharedTabGroup.ColorR\x05\x63olor\x12;\n\x1aoriginating_tab_group_guid\x18\x03 \x01(\tR\x17originatingTabGroupGuid\"x\n\x05\x43olor\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04GREY\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\x12\x07\n\x03RED\x10\x03\x12\n\n\x06YELLOW\x10\x04\x12\t\n\x05GREEN\x10\x05\x12\x08\n\x04PINK\x10\x06\x12\n\n\x06PURPLE\x10\x07\x12\x08\n\x04\x43YAN\x10\x08\x12\n\n\x06ORANGE\x10\t\"\xbb\x01\n\tSharedTab\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x31\n\x15shared_tab_group_guid\x18\x04 \x01(\tR\x12sharedTabGroupGuid\x12@\n\x0funique_position\x18\x05 \x01(\x0b\x32\x17.sync_pb.UniquePositionR\x0euniquePositionJ\x04\x08\x03\x10\x04R\x0b\x66\x61vicon_urlBi\n\x0b\x63om.sync_pbB SharedTabGroupDataSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.shared_tab_group_data_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB SharedTabGroupDataSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_SHAREDTABGROUPDATASPECIFICS']._serialized_start=124
  _globals['_SHAREDTABGROUPDATASPECIFICS']._serialized_end=383
  _globals['_SHAREDTABGROUP']._serialized_start=386
  _globals['_SHAREDTABGROUP']._serialized_end=660
  _globals['_SHAREDTABGROUP_COLOR']._serialized_start=540
  _globals['_SHAREDTABGROUP_COLOR']._serialized_end=660
  _globals['_SHAREDTAB']._serialized_start=663
  _globals['_SHAREDTAB']._serialized_end=850
# @@protoc_insertion_point(module_scope)
