# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/sync_invalidations_payload.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/sync_invalidations_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9components/sync/protocol/sync_invalidations_payload.proto\x12\x07sync_pb\"\xf2\x01\n\x18SyncInvalidationsPayload\x12n\n\x17\x64\x61ta_type_invalidations\x18\x01 \x03(\x0b\x32\x36.sync_pb.SyncInvalidationsPayload.DataTypeInvalidationR\x15\x64\x61taTypeInvalidations\x12\x12\n\x04hint\x18\x02 \x01(\x0cR\x04hint\x12\x18\n\x07version\x18\x03 \x01(\x03R\x07version\x1a\x38\n\x14\x44\x61taTypeInvalidation\x12 \n\x0c\x64\x61ta_type_id\x18\x01 \x01(\x05R\ndataTypeIdBf\n\x0b\x63om.sync_pbB\x1dSyncInvalidationsPayloadProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.sync_invalidations_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\035SyncInvalidationsPayloadProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_SYNCINVALIDATIONSPAYLOAD']._serialized_start=71
  _globals['_SYNCINVALIDATIONSPAYLOAD']._serialized_end=313
  _globals['_SYNCINVALIDATIONSPAYLOAD_DATATYPEINVALIDATION']._serialized_start=257
  _globals['_SYNCINVALIDATIONSPAYLOAD_DATATYPEINVALIDATION']._serialized_end=313
# @@protoc_insertion_point(module_scope)
