# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/tab_group_attribution_metadata.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/tab_group_attribution_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=components/sync/protocol/tab_group_attribution_metadata.proto\x12\x07sync_pb\"\xc6\x02\n\x13\x41ttributionMetadata\x12\x42\n\x07\x63reated\x18\x01 \x01(\x0b\x32(.sync_pb.AttributionMetadata.AttributionR\x07\x63reated\x12\x42\n\x07updated\x18\x02 \x01(\x0b\x32(.sync_pb.AttributionMetadata.AttributionR\x07updated\x1a\xa6\x01\n\x0b\x41ttribution\x12_\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32>.sync_pb.AttributionMetadata.Attribution.AttributionDeviceInfoR\ndeviceInfo\x1a\x36\n\x15\x41ttributionDeviceInfo\x12\x1d\n\ncache_guid\x18\x01 \x01(\tR\tcacheGuidBi\n\x0b\x63om.sync_pbB TabGroupAttributionMetadataProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.tab_group_attribution_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB TabGroupAttributionMetadataProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_ATTRIBUTIONMETADATA']._serialized_start=75
  _globals['_ATTRIBUTIONMETADATA']._serialized_end=401
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION']._serialized_start=235
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION']._serialized_end=401
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION_ATTRIBUTIONDEVICEINFO']._serialized_start=347
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION_ATTRIBUTIONDEVICEINFO']._serialized_end=401
# @@protoc_insertion_point(module_scope)
