# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/test.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#components/sync/protocol/test.proto\x12\x07sync_pb\"&\n\x12UnknownFieldsTestA\x12\x10\n\x03\x66oo\x18\x01 \x02(\x08R\x03\x66oo\"8\n\x12UnknownFieldsTestB\x12\x10\n\x03\x66oo\x18\x01 \x02(\x08R\x03\x66oo\x12\x10\n\x03\x62\x61r\x18\x02 \x02(\x08R\x03\x62\x61rBR\n\x0b\x63om.sync_pbB\tTestProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\tTestProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_UNKNOWNFIELDSTESTA']._serialized_start=48
  _globals['_UNKNOWNFIELDSTESTA']._serialized_end=86
  _globals['_UNKNOWNFIELDSTESTB']._serialized_start=88
  _globals['_UNKNOWNFIELDSTESTB']._serialized_end=144
# @@protoc_insertion_point(module_scope)
