# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/theme_specifics_ios.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/theme_specifics_ios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import theme_types_pb2 as components_dot_sync_dot_protocol_dot_theme__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2components/sync/protocol/theme_specifics_ios.proto\x12\x07sync_pb\x1a*components/sync/protocol/theme_types.proto\"\x9b\x01\n\x11ThemeSpecificsIos\x12\x41\n\x10user_color_theme\x18\x01 \x01(\x0b\x32\x17.sync_pb.UserColorThemeR\x0euserColorTheme\x12\x43\n\x0entp_background\x18\x02 \x01(\x0b\x32\x1c.sync_pb.NtpCustomBackgroundR\rntpBackgroundB_\n\x0b\x63om.sync_pbB\x16ThemeSpecificsIosProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.theme_specifics_ios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\026ThemeSpecificsIosProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_THEMESPECIFICSIOS']._serialized_start=108
  _globals['_THEMESPECIFICSIOS']._serialized_end=263
# @@protoc_insertion_point(module_scope)
