# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/theme_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/theme_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import theme_types_pb2 as components_dot_sync_dot_protocol_dot_theme__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/theme_specifics.proto\x12\x07sync_pb\x1a*components/sync/protocol/theme_types.proto\"\xd3\x06\n\x0eThemeSpecifics\x12(\n\x10use_custom_theme\x18\x01 \x01(\x08R\x0euseCustomTheme\x12<\n\x1buse_system_theme_by_default\x18\x02 \x01(\x08R\x17useSystemThemeByDefault\x12*\n\x11\x63ustom_theme_name\x18\x03 \x01(\tR\x0f\x63ustomThemeName\x12&\n\x0f\x63ustom_theme_id\x18\x04 \x01(\tR\rcustomThemeId\x12\x35\n\x17\x63ustom_theme_update_url\x18\x05 \x01(\tR\x14\x63ustomThemeUpdateUrl\x12m\n\x19\x61utogenerated_color_theme\x18\x06 \x01(\x0b\x32/.sync_pb.ThemeSpecifics.AutogeneratedColorThemeH\x00R\x17\x61utogeneratedColorTheme\x12\x43\n\x10user_color_theme\x18\x07 \x01(\x0b\x32\x17.sync_pb.UserColorThemeH\x00R\x0euserColorTheme\x12W\n\x17grayscale_theme_enabled\x18\x08 \x01(\x0b\x32\x1d.sync_pb.ThemeSpecifics.EmptyH\x00R\x15grayscaleThemeEnabled\x12\\\n\x14\x62rowser_color_scheme\x18\t \x01(\x0e\x32*.sync_pb.ThemeSpecifics.BrowserColorSchemeR\x12\x62rowserColorScheme\x12\x43\n\x0entp_background\x18\n \x01(\x0b\x32\x1c.sync_pb.NtpCustomBackgroundR\rntpBackground\x1a/\n\x17\x41utogeneratedColorTheme\x12\x14\n\x05\x63olor\x18\x01 \x01(\rR\x05\x63olor\x1a\x07\n\x05\x45mpty\"[\n\x12\x42rowserColorScheme\x12$\n BROWSER_COLOR_SCHEME_UNSPECIFIED\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\t\n\x05LIGHT\x10\x02\x12\x08\n\x04\x44\x41RK\x10\x03\x42\x07\n\x05\x63olorB\\\n\x0b\x63om.sync_pbB\x13ThemeSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.theme_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\023ThemeSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_THEMESPECIFICS']._serialized_start=104
  _globals['_THEMESPECIFICS']._serialized_end=955
  _globals['_THEMESPECIFICS_AUTOGENERATEDCOLORTHEME']._serialized_start=797
  _globals['_THEMESPECIFICS_AUTOGENERATEDCOLORTHEME']._serialized_end=844
  _globals['_THEMESPECIFICS_EMPTY']._serialized_start=846
  _globals['_THEMESPECIFICS_EMPTY']._serialized_end=853
  _globals['_THEMESPECIFICS_BROWSERCOLORSCHEME']._serialized_start=855
  _globals['_THEMESPECIFICS_BROWSERCOLORSCHEME']._serialized_end=946
# @@protoc_insertion_point(module_scope)
