# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/theme_types.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/theme_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*components/sync/protocol/theme_types.proto\x12\x07sync_pb\"\x8c\x02\n\x0eUserColorTheme\x12\x14\n\x05\x63olor\x18\x01 \x01(\rR\x05\x63olor\x12_\n\x15\x62rowser_color_variant\x18\x02 \x01(\x0e\x32+.sync_pb.UserColorTheme.BrowserColorVariantR\x13\x62rowserColorVariant\"\x82\x01\n\x13\x42rowserColorVariant\x12%\n!BROWSER_COLOR_VARIANT_UNSPECIFIED\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\x0e\n\nTONAL_SPOT\x10\x02\x12\x0b\n\x07NEUTRAL\x10\x03\x12\x0b\n\x07VIBRANT\x10\x04\x12\x0e\n\nEXPRESSIVE\x10\x05\"\xf0\x02\n\x13NtpCustomBackground\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12,\n\x12\x61ttribution_line_1\x18\x02 \x01(\tR\x10\x61ttributionLine1\x12,\n\x12\x61ttribution_line_2\x18\x03 \x01(\tR\x10\x61ttributionLine2\x12\x34\n\x16\x61ttribution_action_url\x18\x04 \x01(\tR\x14\x61ttributionActionUrl\x12#\n\rcollection_id\x18\x05 \x01(\tR\x0c\x63ollectionId\x12!\n\x0cresume_token\x18\x06 \x01(\tR\x0bresumeToken\x12N\n$refresh_timestamp_unix_epoch_seconds\x18\x07 \x01(\x03R refreshTimestampUnixEpochSeconds\x12\x1d\n\nmain_color\x18\x08 \x01(\rR\tmainColorBX\n\x0b\x63om.sync_pbB\x0fThemeTypesProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.theme_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\017ThemeTypesProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_USERCOLORTHEME']._serialized_start=56
  _globals['_USERCOLORTHEME']._serialized_end=324
  _globals['_USERCOLORTHEME_BROWSERCOLORVARIANT']._serialized_start=194
  _globals['_USERCOLORTHEME_BROWSERCOLORVARIANT']._serialized_end=324
  _globals['_NTPCUSTOMBACKGROUND']._serialized_start=327
  _globals['_NTPCUSTOMBACKGROUND']._serialized_end=695
# @@protoc_insertion_point(module_scope)
