# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/typed_url_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/typed_url_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2components/sync/protocol/typed_url_specifics.proto\x12\x07sync_pb\"\xd5\x01\n\x11TypedUrlSpecifics\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n\x06hidden\x18\x04 \x01(\x08R\x06hidden\x12\x1a\n\x06visits\x18\x07 \x03(\x03\x42\x02\x10\x01R\x06visits\x12/\n\x11visit_transitions\x18\x08 \x03(\x05\x42\x02\x10\x01R\x10visitTransitionsJ\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07R\x0btyped_countR\x05visitR\rvisited_countB_\n\x0b\x63om.sync_pbB\x16TypedUrlSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.typed_url_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\026TypedUrlSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visits']._loaded_options = None
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visits']._serialized_options = b'\020\001'
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visit_transitions']._loaded_options = None
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visit_transitions']._serialized_options = b'\020\001'
  _globals['_TYPEDURLSPECIFICS']._serialized_start=64
  _globals['_TYPEDURLSPECIFICS']._serialized_end=277
# @@protoc_insertion_point(module_scope)
