# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/unencrypted_sharing_message.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/unencrypted_sharing_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:components/sync/protocol/unencrypted_sharing_message.proto\x12\x07sync_pb\"\xbd\x01\n\x19UnencryptedSharingMessage\x12\x1f\n\x0bsender_guid\x18\x01 \x01(\tR\nsenderGuid\x12\x46\n\x10send_tab_message\x18\x02 \x01(\x0b\x32\x1a.sync_pb.SendTabToSelfPushH\x00R\x0esendTabMessage\x12,\n\x12sender_device_name\x18\x03 \x01(\tR\x10senderDeviceNameB\t\n\x07payload\"\x92\x03\n\x11SendTabToSelfPush\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n\x04text\x18\x02 \x01(\tR\x04text\x12\x34\n\x04icon\x18\x03 \x03(\x0b\x32 .sync_pb.SendTabToSelfPush.ImageR\x04icon\x12:\n\x07\x66\x61vicon\x18\x04 \x01(\x0b\x32 .sync_pb.SendTabToSelfPush.ImageR\x07\x66\x61vicon\x12\'\n\x0f\x64\x65stination_url\x18\x05 \x01(\tR\x0e\x64\x65stinationUrl\x12+\n\x11placeholder_title\x18\x06 \x01(\tR\x10placeholderTitle\x12)\n\x10placeholder_body\x18\x07 \x01(\tR\x0fplaceholderBody\x12*\n\x11\x65ntry_unique_guid\x18\x08 \x01(\tR\x0f\x65ntryUniqueGuid\x1a\x34\n\x05Image\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n\x08\x61lt_text\x18\x02 \x01(\tR\x07\x61ltTextBg\n\x0b\x63om.sync_pbB\x1eUnencryptedSharingMessageProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.unencrypted_sharing_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\036UnencryptedSharingMessageProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_UNENCRYPTEDSHARINGMESSAGE']._serialized_start=72
  _globals['_UNENCRYPTEDSHARINGMESSAGE']._serialized_end=261
  _globals['_SENDTABTOSELFPUSH']._serialized_start=264
  _globals['_SENDTABTOSELFPUSH']._serialized_end=666
  _globals['_SENDTABTOSELFPUSH_IMAGE']._serialized_start=614
  _globals['_SENDTABTOSELFPUSH_IMAGE']._serialized_end=666
# @@protoc_insertion_point(module_scope)
