# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/unique_position.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/unique_position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/unique_position.proto\x12\x07sync_pb\"\xc0\x01\n\x0eUniquePosition\x12\x18\n\x05value\x18\x01 \x01(\x0c\x42\x02\x18\x01R\x05value\x12-\n\x10\x63ompressed_value\x18\x02 \x01(\x0c\x42\x02\x18\x01R\x0f\x63ompressedValue\x12\x33\n\x13uncompressed_length\x18\x03 \x01(\x04\x42\x02\x18\x01R\x12uncompressedLength\x12\x30\n\x14\x63ustom_compressed_v1\x18\x04 \x01(\x0cR\x12\x63ustomCompressedV1B\\\n\x0b\x63om.sync_pbB\x13UniquePositionProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.unique_position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\023UniquePositionProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_UNIQUEPOSITION'].fields_by_name['value']._loaded_options = None
  _globals['_UNIQUEPOSITION'].fields_by_name['value']._serialized_options = b'\030\001'
  _globals['_UNIQUEPOSITION'].fields_by_name['compressed_value']._loaded_options = None
  _globals['_UNIQUEPOSITION'].fields_by_name['compressed_value']._serialized_options = b'\030\001'
  _globals['_UNIQUEPOSITION'].fields_by_name['uncompressed_length']._loaded_options = None
  _globals['_UNIQUEPOSITION'].fields_by_name['uncompressed_length']._serialized_options = b'\030\001'
  _globals['_UNIQUEPOSITION']._serialized_start=60
  _globals['_UNIQUEPOSITION']._serialized_end=252
# @@protoc_insertion_point(module_scope)
