# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/web_app_specifics.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'components/sync/protocol/web_app_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0components/sync/protocol/web_app_specifics.proto\x12\x07sync_pb\"\xbe\x01\n\x0eWebAppIconInfo\x12\x1c\n\nsize_in_px\x18\x01 \x01(\x05R\x08sizeInPx\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x39\n\x07purpose\x18\x03 \x01(\x0e\x32\x1f.sync_pb.WebAppIconInfo.PurposeR\x07purpose\"A\n\x07Purpose\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41NY\x10\x01\x12\x0c\n\x08MASKABLE\x10\x02\x12\x0e\n\nMONOCHROME\x10\x03\"\xbd\x05\n\x0fWebAppSpecifics\x12\x1b\n\tstart_url\x18\x01 \x01(\tR\x08startUrl\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x63\n\x19user_display_mode_default\x18\x03 \x01(\x0e\x32(.sync_pb.WebAppSpecifics.UserDisplayModeR\x16userDisplayModeDefault\x12\x1f\n\x0btheme_color\x18\x04 \x01(\rR\nthemeColor\x12\x14\n\x05scope\x18\x05 \x01(\tR\x05scope\x12\x36\n\nicon_infos\x18\x06 \x03(\x0b\x32\x17.sync_pb.WebAppIconInfoR\ticonInfos\x12*\n\x11user_page_ordinal\x18\x07 \x01(\tR\x0fuserPageOrdinal\x12.\n\x13user_launch_ordinal\x18\x08 \x01(\tR\x11userLaunchOrdinal\x12\x30\n\x14relative_manifest_id\x18\t \x01(\tR\x12relativeManifestId\x12]\n\x16user_display_mode_cros\x18\n \x01(\x0e\x32(.sync_pb.WebAppSpecifics.UserDisplayModeR\x13userDisplayModeCros\x12<\n\rtrusted_icons\x18\x0b \x03(\x0b\x32\x17.sync_pb.WebAppIconInfoR\x0ctrustedIcons\"K\n\x0fUserDisplayMode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07\x42ROWSER\x10\x01\x12\x0e\n\nSTANDALONE\x10\x03\x12\n\n\x06TABBED\x10\x06R\x1auser_display_mode_non_crosR\x11user_display_modeB]\n\x0b\x63om.sync_pbB\x14WebAppSpecificsProtoH\x01P\x01\xa2\x02\x03SXX\xaa\x02\x06SyncPb\xca\x02\x06SyncPb\xe2\x02\x12SyncPb\\GPBMetadata\xea\x02\x06SyncPb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.web_app_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.sync_pbB\024WebAppSpecificsProtoH\001P\001\242\002\003SXX\252\002\006SyncPb\312\002\006SyncPb\342\002\022SyncPb\\GPBMetadata\352\002\006SyncPb'
  _globals['_WEBAPPICONINFO']._serialized_start=62
  _globals['_WEBAPPICONINFO']._serialized_end=252
  _globals['_WEBAPPICONINFO_PURPOSE']._serialized_start=187
  _globals['_WEBAPPICONINFO_PURPOSE']._serialized_end=252
  _globals['_WEBAPPSPECIFICS']._serialized_start=255
  _globals['_WEBAPPSPECIFICS']._serialized_end=956
  _globals['_WEBAPPSPECIFICS_USERDISPLAYMODE']._serialized_start=834
  _globals['_WEBAPPSPECIFICS_USERDISPLAYMODE']._serialized_end=909
# @@protoc_insertion_point(module_scope)
